spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
open-weather-api:
  api-url: 'http://testURL/data/2.5/weather?q={city}&APPID={appid}'
  app-id: 'testAppId'

